### ISSUE TITLE
Change restaurant_employee_user model

### ISSUE THREAD

**Issue by Colima-97** [lemon-labs-mx/Xolo-Backend#13]
**src/models/restaurant_employee_user.js**

Well, we have some silly errors:

![image](https://user-images.githubusercontent.com/22593949/65566130-91827a80-df17-11e9-8b40-c8a7adead3bf.png)

![image](https://user-images.githubusercontent.com/22593949/65566143-9cd5a600-df17-11e9-9d28-62743300df51.png)

We must change these names:

- DeliverymanSchema => RestaurantEmployeeUser
- 'deliveryman' => 'restaurant_employee_user'
- DeliverymanSchema => RestaurantEmployeeUser

Those names are only options, you can choose others instead but with the same meaning.

**Comment by 15mgm15** [comment]
I'm fine with those changes and names :)
