### ISSUE TITLE
[Future Feature] Company Third Party Model is Needed (SP3-005)

### ISSUE THREAD

**Issue by Colima-97** [lemon-labs-mx/Xolo-Backend#19]
Hello guys, I was making the method to get the **Deliveryman Profile**...

![image](https://user-images.githubusercontent.com/22593949/66248574-cea3f500-e6ed-11e9-99ee-8b57eb24faba.png)

and just realized that, it could be not helpful but obvious to have the name of the company where the Deliveryman is currently working on, isn't it?

I had the idea of getting the name of the company by doing this:

- Making a "middleware" (it's just a function) that gets the `code` (remember that each Deliveryman has a `code`) of the deliveryman and then, it goes and seeks within **Restaurant** and **Company Third Party** Model and finally returns the Company Name, and here is where the tittle makes sense.

For the moment, it could stay like this:

![image](https://user-images.githubusercontent.com/22593949/66248574-cea3f500-e6ed-11e9-99ee-8b57eb24faba.png)

but I wanted to remark and leave evidence of that.

**Remarkable stuff**
- We already have **CTP** model, but it's not complete
- I could seek the `code` within **3rd Party Admin User** but I think it's a bad practice
- Yeah! I wrote this letter just to remember to do this in the future, plz don't kick me out of the team

**Comment by 15mgm15** [comment]
It makes sense lets implement it 👍
